version: '3.8'

services:
  app:
    build: .
    container_name: finance-app
    ports:
      - "5000:5000"
    environment:
      - ENV_VAR=value
    volumes:
      - .:/app
    depends_on:
      - db
