version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    depends_on:
      - finance-db

  finance-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance_db
    volumes:
      - financeai_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  financeai_postgres_data:
