version: '3'

services:
  db:
    image: postgres:latest
    container_name: finance-db   # Nome do container do banco de dados
    environment:
      POSTGRES_USER: Andre
      POSTGRES_PASSWORD: Aa22111988
      POSTGRES_DB: finance_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: finance-app  # Nome do container da aplicação
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  postgres_data:
